# Generated by Django 5.0.3 on 2024-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_payment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_key',
            field=models.CharField(default='sdsfsfsdfsfSF', max_length=255),
            preserve_default=False,
        ),
    ]
