# Generated by Django 5.0.3 on 2024-11-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_payment_created_at_subscriptions_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('by_number', 'Number'), ('by_week', 'Week'), ('by_month', 'Month')], default='by_week', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
