# Generated by Django 5.0.3 on 2024-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_payment_subscription_type_subscriptions_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
