# Generated by Django 5.0.3 on 2024-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='amount_of_copies',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
