# Generated by Django 5.1.4 on 2024-12-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0007_alter_subscriptions_amount_of_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('by_number', 'Number'), ('by_week', 'Week'), ('by_month', 'Month')], max_length=255, null=True),
        ),
    ]
