# Generated by Django 5.1.4 on 2024-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0009_alter_subscriptions_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('by_number', 'Number'), ('by_week', 'Week'), ('by_month', 'Month'), ('Donation', 'Donation')], default='Donation', max_length=255),
        ),
    ]
