# Generated by Django 5.1.4 on 2024-12-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0010_alter_payment_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_number',
            field=models.CharField(default='00000000000', max_length=255),
        ),
    ]
