# Generated by Django 5.1.4 on 2024-12-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0011_payment_paid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_kind',
            field=models.CharField(default='Cash In', max_length=50),
        ),
    ]
