# Generated by Django 5.1.4 on 2025-04-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0012_payment_transaction_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
