# Generated by Django 5.0.3 on 2024-04-05 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSkillChoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('recommended', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(choices=[('pianist', 'Pianist'), ('Singer', 'Singer'), ('conductor', 'Conductor'), ('Organist', 'Organist'), ('Vocalist', 'Vocal Coach'), ('Soloist', 'Soloist')], to='Musicians.musicskillchoices')),
            ],
        ),
    ]
