# Generated by Django 5.0.3 on 2024-11-30 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians', '0004_alter_musicianmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianmodel',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
