# Generated by Django 5.0.3 on 2024-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians', '0005_musicianmodel_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='skills',
            field=models.ManyToManyField(related_name='musician', to='Musicians.musicskillchoices'),
        ),
    ]
