# Generated by Django 5.1.4 on 2024-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians', '0006_alter_musicianmodel_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
