# Generated by Django 5.0.3 on 2024-04-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='musician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.ImageField(null=True, upload_to='Profile'),
        ),
    ]
