# Generated by Django 5.0.3 on 2024-11-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_users_phone_number_alter_users_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
