# Generated by Django 5.0.3 on 2024-03-19 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(default='Ibihe Bisanzwe', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='copies',
            name='document',
            field=models.FileField(upload_to='songs_docs'),
        ),
        migrations.AddField(
            model_name='copies',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Documents.songtype'),
        ),
    ]
