# Generated by Django 5.0.3 on 2024-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_songtype_alter_copies_document_copies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtype',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='Song_Type'),
        ),
    ]
