# Generated by Django 5.0.3 on 2024-04-27 07:43

import Documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_alter_copies_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='document',
            field=models.FileField(upload_to=Documents.models.song_upload_path),
        ),
    ]
