# Generated by Django 5.0.3 on 2024-09-30 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_alter_copies_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Others', max_length=255, unique=True)),
            ],
        ),
    ]
