# Generated by Django 5.0.3 on 2024-09-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_songcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Documents.songcategory'),
        ),
    ]
