# Generated by Django 5.0.3 on 2024-11-30 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_alter_copies_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='copies',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
