# Generated by Django 5.0.3 on 2024-12-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0008_copies_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.songtype'),
        ),
    ]
