# Generated by Django 5.0.3 on 2024-12-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0009_alter_copies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.songcategory'),
        ),
    ]
