# Generated by Django 5.0.3 on 2024-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0011_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='composer',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='copies',
            name='name',
            field=models.CharField(max_length=2550),
        ),
    ]
