# Generated by Django 5.0.3 on 2024-12-07 08:35

import Documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0014_alter_songcategory_name_alter_songtype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='document',
            field=models.FileField(max_length=10000, upload_to=Documents.models.song_upload_path),
        ),
    ]
