# Generated by Django 5.1.4 on 2024-12-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0017_alter_request_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='copies',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
