# Generated by Django 5.1.4 on 2025-04-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0018_copies_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'App Version',
                'ordering': ['-created_at'],
            },
        ),
    ]
