# Generated by Django 5.0.3 on 2024-04-07 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSongs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='Trending_Songs')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
