# Generated by Django 5.0.3 on 2024-10-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertise', '0003_event_created_at_event_date_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingsongs',
            name='thumbnail',
        ),
    ]
