# Generated by Django 5.0.3 on 2024-04-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodal',
            options={},
        ),
    ]
