# Generated by Django 5.0.3 on 2024-04-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='video',
            field=models.ForeignKey(default='167ebc17-87cc-45b6-8f51-f8b4e4e1196d', on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to='Shorts.video'),
            preserve_default=False,
        ),
    ]
